version: "3.8"
services:
  api:
    container_name: nest_todo
    env_file:
      - .development.env
    build: .
    tty: true
    ports:
      - "3090:3090"
    volumes:
      - type: bind
        source: .
        target: /backend
  mysql:
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3310:3306
    expose:
      - 3310
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nesttodo
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3310
    volumes:
      - /var/lib/mysql